#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

rm -rf "$ROOT/adapters"
"$ROOT/scripts/sync.sh"

test -f "$ROOT/adapters/codex/SKILL.md"
test -f "$ROOT/adapters/codex/agents/openai.yaml"
test -f "$ROOT/adapters/claude/CLAUDE.md"
test -f "$ROOT/adapters/copilot/copilot-instructions.md"
test -f "$ROOT/adapters/gemini/GEMINI.md"

grep -q '^<!-- Generated by scripts/sync.sh; source_sha256: ' "$ROOT/adapters/codex/SKILL.md"
grep -q '^# Generated by scripts/sync.sh; source_sha256: ' "$ROOT/adapters/codex/agents/openai.yaml"
grep -q '^# API Flow Tester for Claude$' "$ROOT/adapters/claude/CLAUDE.md"
grep -q '^# API Flow Tester for Copilot$' "$ROOT/adapters/copilot/copilot-instructions.md"
grep -q '^# API Flow Tester for Gemini$' "$ROOT/adapters/gemini/GEMINI.md"

for adapter in codex claude copilot gemini; do
  test -f "$ROOT/adapters/$adapter/references/example-flow.md"
  test -f "$ROOT/adapters/$adapter/references/example-negative-flow.md"
  test -f "$ROOT/adapters/$adapter/references/example-otp-flow.md"
  test -f "$ROOT/adapters/$adapter/references/flow-test-env.example"
done
